[package]
name = "blog_os"
version = "0.1.0"
authors = ["Jakob Waibel <mail@jakobwaibel.com>"]

# the profile used for `cargo build`
[profile.dev]
panic = "abort" # disable stack unwinding on panic

# the profile used for `cargo build --release`
[profile.release]
panic = "abort" # disable stack unwinding on panic

edition = "2018"
[dependencies]
bootloader = "0.9.8"
volatile = "0.2.6"
spin = "0.5.2"

[build]
target = "x86_64-blog_os.json"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]