apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server
spec:
  selector:
    matchLabels:
      app: tcp-server
  replicas: 1 
  template:
    metadata:
      labels:
        app: tcp-server
    spec:
      containers:
      - name: tcp-server
        image: jakwai01/tcp-server
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:  
  name: my-nodeport-service
spec:
  selector:    
    app: tcp-server
  type: NodePort
  ports:  
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30036
    protocol: TCP